service: appsync-elasticsearch

frameworkVersion: ">=1.40.0 <2.0.0"

plugins:
  - serverless-appsync-plugin
  - serverless-pseudo-parameters

provider:
  name: aws
  stage: ${opt:stage, 'development'}
  region: ap-northeast-1
  logRetentionInDays: 7

custom:
  config: ${file(./config.${self:provider.stage}.yml)}
  appSync:
    serviceRole: AppSyncServiceRole
    name: ${self:service.name}-${self:provider.stage}
    authenticationType: API_KEY # API_KEY or AWS_IAM or AMAZON_COGNITO_USER_POOLS or OPENID_CONNECT
    logConfig:
      level: ERROR # Logging Level: NONE | ERROR | ALL
    mappingTemplates:
      - dataSource: Elasticsearch
        type: Query
        field: searchArticles
        request: searchArticles-request-mapping-template.vtl
        response: searchArticles-response-mapping-template.vtl
      - dataSource: Elasticsearch
        type: Query
        field: article
        request: article-request-mapping-template.vtl
        response: article-response-mapping-template.vtl
    dataSources:
      - type: AMAZON_ELASTICSEARCH
        name: Elasticsearch
        description: 'Elasticsearch'
        config:
          endpoint: ${self:custom.config.elasticsearchEndpoint}
